// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = BlogPostSlice;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>
  /**
   * Meta Description field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type PageDocumentDataSlicesSlice =
  | HomeBaneerSlice
  | PractiseAreaSlice
  | HomeValuesSlice
  | CtaSlice
  | CommercialBannerSlice
  | ClientsRepresentSlice
  | TwoColWithImageSlice
  | PreFooterSlice
  | HeaderWithButtonsSlice
  | TickListSlice
  | RepuTationBlockSlice
  | SimpleTwoColumnSlice
  | FaqSlice
  | ColumnWithFaqSlice
  | RepresentativeColumnSlice
  | BannerWithBackgroundImageSlice
  | FaqWIthTitleSlice
  | RichTextWithButtonSlice
  | AppealSectionSlice
  | IconBoxSlice
  | ResultsSlice
  | TeamSlice
  | SingleTeamPageSlice
  | PageHeadingBannerSlice
  | OfficesSlice
  | SingleOfficePageSlice
  | GallerySlice
  | BadgesSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * global field in *page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.global
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  global: prismic.ContentRelationshipField<"settings">;

  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * full logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.full_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  full_logo: prismic.ImageField<never>;

  /**
   * fav field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fav
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fav: prismic.ImageField<never>;

  /**
   * Slice Zone field in *settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type TeamDocumentDataSlicesSlice = SingleTeamPageSlice;

/**
 * Content for team documents
 */
interface TeamDocumentData {
  /**
   * title field in *team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *team*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeamDocumentDataSlicesSlice>
  /**
   * Meta Description field in *team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: team.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: team.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * team document from Prismic
 *
 * - **API ID**: `team`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TeamDocumentData>, "team", Lang>;

export type AllDocumentTypes =
  | BlogDocument
  | PageDocument
  | SettingsDocument
  | TeamDocument;

/**
 * Primary content in *AppealSection → Primary*
 */
export interface AppealSectionSliceDefaultPrimary {
  /**
   * subtitle field in *AppealSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: appeal_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *AppealSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: appeal_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *AppealSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: appeal_section.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *AppealSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: appeal_section.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AppealSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AppealSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AppealSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AppealSection*
 */
type AppealSectionSliceVariation = AppealSectionSliceDefault;

/**
 * AppealSection Shared Slice
 *
 * - **API ID**: `appeal_section`
 * - **Description**: AppealSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AppealSectionSlice = prismic.SharedSlice<
  "appeal_section",
  AppealSectionSliceVariation
>;

/**
 * Primary content in *Badges → Items*
 */
export interface BadgesSliceDefaultItem {
  /**
   * image field in *Badges → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: badges.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Badges Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BadgesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BadgesSliceDefaultItem>
>;

/**
 * Slice variation for *Badges*
 */
type BadgesSliceVariation = BadgesSliceDefault;

/**
 * Badges Shared Slice
 *
 * - **API ID**: `badges`
 * - **Description**: Badges
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BadgesSlice = prismic.SharedSlice<"badges", BadgesSliceVariation>;

/**
 * Primary content in *BannerWithBackgroundImage → Primary*
 */
export interface BannerWithBackgroundImageSliceDefaultPrimary {
  /**
   * background imge field in *BannerWithBackgroundImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_with_background_image.primary.bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;

  /**
   * subtitle field in *BannerWithBackgroundImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_with_background_image.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *BannerWithBackgroundImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_with_background_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *BannerWithBackgroundImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_with_background_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *BannerWithBackgroundImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_with_background_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BannerWithBackgroundImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerWithBackgroundImageSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<BannerWithBackgroundImageSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *BannerWithBackgroundImage*
 */
type BannerWithBackgroundImageSliceVariation =
  BannerWithBackgroundImageSliceDefault;

/**
 * BannerWithBackgroundImage Shared Slice
 *
 * - **API ID**: `banner_with_background_image`
 * - **Description**: BannerWithBackgroundImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerWithBackgroundImageSlice = prismic.SharedSlice<
  "banner_with_background_image",
  BannerWithBackgroundImageSliceVariation
>;

/**
 * Primary content in *BlogPost → Primary*
 */
export interface BlogPostSliceDefaultPrimary {
  /**
   * title field in *BlogPost → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * published at field in *BlogPost → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.primary.published_at
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_at: prismic.DateField;

  /**
   * short text field in *BlogPost → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.primary.short_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  short_text: prismic.RichTextField;

  /**
   * featured image field in *BlogPost → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * body text field in *BlogPost → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.primary.body_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_text: prismic.RichTextField;
}

/**
 * Primary content in *BlogPost → Items*
 */
export interface BlogPostSliceDefaultItem {
  /**
   * tag field in *BlogPost → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.items[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Default variation for BlogPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostSliceDefaultPrimary>,
  Simplify<BlogPostSliceDefaultItem>
>;

/**
 * Slice variation for *BlogPost*
 */
type BlogPostSliceVariation = BlogPostSliceDefault;

/**
 * BlogPost Shared Slice
 *
 * - **API ID**: `blog_post`
 * - **Description**: BlogPost
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSlice = prismic.SharedSlice<
  "blog_post",
  BlogPostSliceVariation
>;

/**
 * Primary content in *ClientsRepresent → Primary*
 */
export interface ClientsRepresentSliceDefaultPrimary {
  /**
   * title field in *ClientsRepresent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_represent.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *ClientsRepresent → Items*
 */
export interface ClientsRepresentSliceDefaultItem {
  /**
   * text field in *ClientsRepresent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_represent.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for ClientsRepresent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsRepresentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClientsRepresentSliceDefaultPrimary>,
  Simplify<ClientsRepresentSliceDefaultItem>
>;

/**
 * Primary content in *ClientsRepresent → Primary*
 */
export interface ClientsRepresentSliceListLeftAlignPrimary {
  /**
   * title field in *ClientsRepresent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_represent.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *ClientsRepresent → Items*
 */
export interface ClientsRepresentSliceListLeftAlignItem {
  /**
   * text field in *ClientsRepresent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_represent.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * List Left Align variation for ClientsRepresent Slice
 *
 * - **API ID**: `listLeftAlign`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsRepresentSliceListLeftAlign = prismic.SharedSliceVariation<
  "listLeftAlign",
  Simplify<ClientsRepresentSliceListLeftAlignPrimary>,
  Simplify<ClientsRepresentSliceListLeftAlignItem>
>;

/**
 * Slice variation for *ClientsRepresent*
 */
type ClientsRepresentSliceVariation =
  | ClientsRepresentSliceDefault
  | ClientsRepresentSliceListLeftAlign;

/**
 * ClientsRepresent Shared Slice
 *
 * - **API ID**: `clients_represent`
 * - **Description**: ClientsRepresent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsRepresentSlice = prismic.SharedSlice<
  "clients_represent",
  ClientsRepresentSliceVariation
>;

/**
 * Primary content in *ColumnWithFaq → Primary*
 */
export interface ColumnWithFaqSliceDefaultPrimary {
  /**
   * image field in *ColumnWithFaq → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: column_with_faq.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *ColumnWithFaq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: column_with_faq.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *ColumnWithFaq → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: column_with_faq.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *ColumnWithFaq → Items*
 */
export interface ColumnWithFaqSliceDefaultItem {
  /**
   * title field in *ColumnWithFaq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: column_with_faq.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *ColumnWithFaq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: column_with_faq.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for ColumnWithFaq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ColumnWithFaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ColumnWithFaqSliceDefaultPrimary>,
  Simplify<ColumnWithFaqSliceDefaultItem>
>;

/**
 * Slice variation for *ColumnWithFaq*
 */
type ColumnWithFaqSliceVariation = ColumnWithFaqSliceDefault;

/**
 * ColumnWithFaq Shared Slice
 *
 * - **API ID**: `column_with_faq`
 * - **Description**: ColumnWithFaq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ColumnWithFaqSlice = prismic.SharedSlice<
  "column_with_faq",
  ColumnWithFaqSliceVariation
>;

/**
 * Primary content in *CommercialBanner → Primary*
 */
export interface CommercialBannerSliceDefaultPrimary {
  /**
   * subtitle field in *CommercialBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: commercial_banner.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *CommercialBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: commercial_banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *CommercialBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: commercial_banner.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * second column title field in *CommercialBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: commercial_banner.primary.second_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_title: prismic.KeyTextField;
}

/**
 * Primary content in *CommercialBanner → Items*
 */
export interface CommercialBannerSliceDefaultItem {
  /**
   * title field in *CommercialBanner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: commercial_banner.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * link field in *CommercialBanner → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: commercial_banner.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * disabled field in *CommercialBanner → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: commercial_banner.items[].disabled
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  disabled: prismic.BooleanField;
}

/**
 * Default variation for CommercialBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommercialBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CommercialBannerSliceDefaultPrimary>,
  Simplify<CommercialBannerSliceDefaultItem>
>;

/**
 * Slice variation for *CommercialBanner*
 */
type CommercialBannerSliceVariation = CommercialBannerSliceDefault;

/**
 * CommercialBanner Shared Slice
 *
 * - **API ID**: `commercial_banner`
 * - **Description**: CommercialBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommercialBannerSlice = prismic.SharedSlice<
  "commercial_banner",
  CommercialBannerSliceVariation
>;

/**
 * Primary content in *Cta → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * title field in *Cta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * image field in *Cta → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * title field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Faq → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * title field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *FaqWIthTitle → Primary*
 */
export interface FaqWIthTitleSliceDefaultPrimary {
  /**
   * title field in *FaqWIthTitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_w_ith_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *FaqWIthTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_w_ith_title.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *FaqWIthTitle → Items*
 */
export interface FaqWIthTitleSliceDefaultItem {
  /**
   * title field in *FaqWIthTitle → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_w_ith_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *FaqWIthTitle → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_w_ith_title.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for FaqWIthTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqWIthTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqWIthTitleSliceDefaultPrimary>,
  Simplify<FaqWIthTitleSliceDefaultItem>
>;

/**
 * Slice variation for *FaqWIthTitle*
 */
type FaqWIthTitleSliceVariation = FaqWIthTitleSliceDefault;

/**
 * FaqWIthTitle Shared Slice
 *
 * - **API ID**: `faq_w_ith_title`
 * - **Description**: FaqWIthTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqWIthTitleSlice = prismic.SharedSlice<
  "faq_w_ith_title",
  FaqWIthTitleSliceVariation
>;

/**
 * Primary content in *Gallery → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * padding field in *Gallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  padding: prismic.KeyTextField;
}

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * image field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *HeaderWithButtons → Primary*
 */
export interface HeaderWithButtonsSliceDefaultPrimary {
  /**
   * background image field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * gradient field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: linear-gradient(64deg, #ffffff 31%, rgba(255, 255, 255, 0) 80% )
   * - **API ID Path**: header_with_buttons.primary.gradient
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  gradient: prismic.SelectField<
    | "linear-gradient(64deg, #ffffff 31%, rgba(255, 255, 255, 0) 80% )"
    | "linear-gradient(64deg, rgb(255, 255, 255) 31%, rgba(255, 255, 255, 0.45) 80%)",
    "filled"
  >;

  /**
   * subtitle field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * small text field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.small_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  small_text: prismic.RichTextField;

  /**
   * button text 1 field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.button_text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_1: prismic.KeyTextField;

  /**
   * button link 1 field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.button_link_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_1: prismic.LinkField;

  /**
   * button text 2 field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_2: prismic.KeyTextField;

  /**
   * button link 2 field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.button_link_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_2: prismic.LinkField;

  /**
   * text field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * second col title field in *HeaderWithButtons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.primary.second_col_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_col_title: prismic.KeyTextField;
}

/**
 * Primary content in *HeaderWithButtons → Items*
 */
export interface HeaderWithButtonsSliceDefaultItem {
  /**
   * button title field in *HeaderWithButtons → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.items[].button_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_title: prismic.KeyTextField;

  /**
   * button link field in *HeaderWithButtons → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_with_buttons.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * disabled field in *HeaderWithButtons → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: header_with_buttons.items[].disabled
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  disabled: prismic.BooleanField;
}

/**
 * Default variation for HeaderWithButtons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderWithButtonsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderWithButtonsSliceDefaultPrimary>,
  Simplify<HeaderWithButtonsSliceDefaultItem>
>;

/**
 * Slice variation for *HeaderWithButtons*
 */
type HeaderWithButtonsSliceVariation = HeaderWithButtonsSliceDefault;

/**
 * HeaderWithButtons Shared Slice
 *
 * - **API ID**: `header_with_buttons`
 * - **Description**: HeaderWithButtons
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderWithButtonsSlice = prismic.SharedSlice<
  "header_with_buttons",
  HeaderWithButtonsSliceVariation
>;

/**
 * Primary content in *HomeBaneer → Primary*
 */
export interface HomeBaneerSliceDefaultPrimary {
  /**
   * image field in *HomeBaneer → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_baneer.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * mbImage field in *HomeBaneer → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_baneer.primary.mbimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mbimage: prismic.ImageField<never>;

  /**
   * subtitle field in *HomeBaneer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_baneer.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *HomeBaneer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_baneer.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *HomeBaneer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_baneer.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for HomeBaneer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeBaneerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeBaneerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeBaneer*
 */
type HomeBaneerSliceVariation = HomeBaneerSliceDefault;

/**
 * HomeBaneer Shared Slice
 *
 * - **API ID**: `home_baneer`
 * - **Description**: HomeBaneer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeBaneerSlice = prismic.SharedSlice<
  "home_baneer",
  HomeBaneerSliceVariation
>;

/**
 * Primary content in *HomeValues → Primary*
 */
export interface HomeValuesSliceDefaultPrimary {
  /**
   * logo field in *HomeValues → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_values.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * title field in *HomeValues → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_values.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *HomeValues → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_values.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *HomeValues → Items*
 */
export interface HomeValuesSliceDefaultItem {
  /**
   * title field in *HomeValues → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_values.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * name field in *HomeValues → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_values.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * position field in *HomeValues → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_values.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * text field in *HomeValues → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_values.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * icon field in *HomeValues → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_values.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Default variation for HomeValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeValuesSliceDefaultPrimary>,
  Simplify<HomeValuesSliceDefaultItem>
>;

/**
 * Slice variation for *HomeValues*
 */
type HomeValuesSliceVariation = HomeValuesSliceDefault;

/**
 * HomeValues Shared Slice
 *
 * - **API ID**: `home_values`
 * - **Description**: HomeValues
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeValuesSlice = prismic.SharedSlice<
  "home_values",
  HomeValuesSliceVariation
>;

/**
 * Primary content in *IconBox → Primary*
 */
export interface IconBoxSliceDefaultPrimary {
  /**
   * title field in *IconBox → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_box.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *IconBox → Items*
 */
export interface IconBoxSliceDefaultItem {
  /**
   * column field in *IconBox → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: icon_box.items[].column
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column: prismic.SelectField<"1" | "2" | "3", "filled">;

  /**
   * icon field in *IconBox → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_box.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * title field in *IconBox → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_box.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *IconBox → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_box.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * name field in *IconBox → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_box.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * position field in *IconBox → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_box.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;
}

/**
 * Default variation for IconBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconBoxSliceDefaultPrimary>,
  Simplify<IconBoxSliceDefaultItem>
>;

/**
 * Slice variation for *IconBox*
 */
type IconBoxSliceVariation = IconBoxSliceDefault;

/**
 * IconBox Shared Slice
 *
 * - **API ID**: `icon_box`
 * - **Description**: IconBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconBoxSlice = prismic.SharedSlice<
  "icon_box",
  IconBoxSliceVariation
>;

/**
 * Primary content in *Offices → Items*
 */
export interface OfficesSliceDefaultItem {
  /**
   * link sub page field in *Offices → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: offices.items[].link_sub_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_sub_page: prismic.LinkField;

  /**
   * image field in *Offices → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offices.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Offices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offices.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * short text field in *Offices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offices.items[].short_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  short_text: prismic.RichTextField;

  /**
   * address field in *Offices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offices.items[].address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * phone field in *Offices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offices.items[].phone
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone: prismic.RichTextField;

  /**
   * Directions field in *Offices → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: offices.items[].directions
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  directions: prismic.LinkField;
}

/**
 * Default variation for Offices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OfficesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<OfficesSliceDefaultItem>
>;

/**
 * Slice variation for *Offices*
 */
type OfficesSliceVariation = OfficesSliceDefault;

/**
 * Offices Shared Slice
 *
 * - **API ID**: `offices`
 * - **Description**: Offices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OfficesSlice = prismic.SharedSlice<
  "offices",
  OfficesSliceVariation
>;

/**
 * Primary content in *PageHeadingBanner → Primary*
 */
export interface PageHeadingBannerSliceDefaultPrimary {
  /**
   * Title field in *PageHeadingBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_heading_banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for PageHeadingBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeadingBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeadingBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHeadingBanner*
 */
type PageHeadingBannerSliceVariation = PageHeadingBannerSliceDefault;

/**
 * PageHeadingBanner Shared Slice
 *
 * - **API ID**: `page_heading_banner`
 * - **Description**: PageHeadingBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeadingBannerSlice = prismic.SharedSlice<
  "page_heading_banner",
  PageHeadingBannerSliceVariation
>;

/**
 * Primary content in *PractiseArea → Primary*
 */
export interface PractiseAreaSliceDefaultPrimary {
  /**
   * topBar field in *PractiseArea → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: practise_area.primary.topbar
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  topbar: prismic.RichTextField;
}

/**
 * Primary content in *PractiseArea → Items*
 */
export interface PractiseAreaSliceDefaultItem {
  /**
   * image field in *PractiseArea → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: practise_area.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *PractiseArea → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: practise_area.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * link field in *PractiseArea → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: practise_area.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for PractiseArea Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PractiseAreaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PractiseAreaSliceDefaultPrimary>,
  Simplify<PractiseAreaSliceDefaultItem>
>;

/**
 * Slice variation for *PractiseArea*
 */
type PractiseAreaSliceVariation = PractiseAreaSliceDefault;

/**
 * PractiseArea Shared Slice
 *
 * - **API ID**: `practise_area`
 * - **Description**: PractiseArea
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PractiseAreaSlice = prismic.SharedSlice<
  "practise_area",
  PractiseAreaSliceVariation
>;

/**
 * Primary content in *PreFooter → Primary*
 */
export interface PreFooterSliceDefaultPrimary {
  /**
   * button text field in *PreFooter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *PreFooter → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * button 2 text field in *PreFooter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.primary.button_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField;

  /**
   * button 2 link field in *PreFooter → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.primary.button_2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_link: prismic.LinkField;
}

/**
 * Primary content in *PreFooter → Items*
 */
export interface PreFooterSliceDefaultItem {
  /**
   * title field in *PreFooter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * icon field in *PreFooter → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * text field in *PreFooter → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * name field in *PreFooter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * position field in *PreFooter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_footer.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;
}

/**
 * Default variation for PreFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PreFooterSliceDefaultPrimary>,
  Simplify<PreFooterSliceDefaultItem>
>;

/**
 * Slice variation for *PreFooter*
 */
type PreFooterSliceVariation = PreFooterSliceDefault;

/**
 * PreFooter Shared Slice
 *
 * - **API ID**: `pre_footer`
 * - **Description**: PreFooter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreFooterSlice = prismic.SharedSlice<
  "pre_footer",
  PreFooterSliceVariation
>;

/**
 * Primary content in *RepresentativeColumn → Primary*
 */
export interface RepresentativeColumnSliceDefaultPrimary {
  /**
   * title field in *RepresentativeColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: representative_column.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *RepresentativeColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: representative_column.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *RepresentativeColumn → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: representative_column.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * bottom image title field in *RepresentativeColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: representative_column.primary.image_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_title: prismic.KeyTextField;

  /**
   * Bottom image text field in *RepresentativeColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: representative_column.primary.bottom_image_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_image_text: prismic.RichTextField;
}

/**
 * Primary content in *RepresentativeColumn → Items*
 */
export interface RepresentativeColumnSliceDefaultItem {
  /**
   * state field in *RepresentativeColumn → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: representative_column.items[].state
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  state: prismic.KeyTextField;
}

/**
 * Default variation for RepresentativeColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RepresentativeColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RepresentativeColumnSliceDefaultPrimary>,
  Simplify<RepresentativeColumnSliceDefaultItem>
>;

/**
 * Slice variation for *RepresentativeColumn*
 */
type RepresentativeColumnSliceVariation = RepresentativeColumnSliceDefault;

/**
 * RepresentativeColumn Shared Slice
 *
 * - **API ID**: `representative_column`
 * - **Description**: RepresentativeColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RepresentativeColumnSlice = prismic.SharedSlice<
  "representative_column",
  RepresentativeColumnSliceVariation
>;

/**
 * Primary content in *RepuTationBlock → Primary*
 */
export interface RepuTationBlockSliceDefaultPrimary {
  /**
   * title field in *RepuTationBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *RepuTationBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * button text 1 field in *RepuTationBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.primary.button_text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_1: prismic.KeyTextField;

  /**
   * button link 1 field in *RepuTationBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.primary.button_link_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_1: prismic.LinkField;

  /**
   * button text 2 field in *RepuTationBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_2: prismic.KeyTextField;

  /**
   * button link 2 field in *RepuTationBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.primary.button_link_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_link_2: prismic.KeyTextField;
}

/**
 * Primary content in *RepuTationBlock → Items*
 */
export interface RepuTationBlockSliceDefaultItem {
  /**
   * icon field in *RepuTationBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * title field in *RepuTationBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *RepuTationBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * name field in *RepuTationBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * position field in *RepuTationBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repu_tation_block.items[].position
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  position: prismic.RichTextField;
}

/**
 * Default variation for RepuTationBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RepuTationBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RepuTationBlockSliceDefaultPrimary>,
  Simplify<RepuTationBlockSliceDefaultItem>
>;

/**
 * Slice variation for *RepuTationBlock*
 */
type RepuTationBlockSliceVariation = RepuTationBlockSliceDefault;

/**
 * RepuTationBlock Shared Slice
 *
 * - **API ID**: `repu_tation_block`
 * - **Description**: RepuTationBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RepuTationBlockSlice = prismic.SharedSlice<
  "repu_tation_block",
  RepuTationBlockSliceVariation
>;

/**
 * Primary content in *Resources → Primary*
 */
export interface ResourcesSliceDefaultPrimary {
  /**
   * title field in *Resources → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * column 1 title field in *Resources → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.primary.column_1_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_1_title: prismic.KeyTextField;

  /**
   * column 2 title field in *Resources → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.primary.column_2_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_2_title: prismic.KeyTextField;
}

/**
 * Primary content in *Resources → Items*
 */
export interface ResourcesSliceDefaultItem {
  /**
   * column field in *Resources → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.items[].column
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column: prismic.SelectField<"coluimn_1" | "coluimn_2">;

  /**
   * title field in *Resources → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * link field in *Resources → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: resources.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Resources Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResourcesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResourcesSliceDefaultPrimary>,
  Simplify<ResourcesSliceDefaultItem>
>;

/**
 * Slice variation for *Resources*
 */
type ResourcesSliceVariation = ResourcesSliceDefault;

/**
 * Resources Shared Slice
 *
 * - **API ID**: `resources`
 * - **Description**: Resources
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResourcesSlice = prismic.SharedSlice<
  "resources",
  ResourcesSliceVariation
>;

/**
 * Primary content in *PageHeadings → Primary*
 */
export interface ResultsSliceDefaultPrimary {
  /**
   * icon field in *PageHeadings → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: results.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * title field in *PageHeadings → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *PageHeadings → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *PageHeadings → Items*
 */
export interface ResultsSliceDefaultItem {
  /**
   * ids field in *PageHeadings → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.items[].ids
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ids: prismic.KeyTextField;

  /**
   * filter title field in *PageHeadings → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.items[].filter_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  filter_title: prismic.KeyTextField;

  /**
   * filter link field in *PageHeadings → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: results.items[].filter_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  filter_link: prismic.LinkField;
}

/**
 * Default variation for PageHeadings Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResultsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResultsSliceDefaultPrimary>,
  Simplify<ResultsSliceDefaultItem>
>;

/**
 * Slice variation for *PageHeadings*
 */
type ResultsSliceVariation = ResultsSliceDefault;

/**
 * PageHeadings Shared Slice
 *
 * - **API ID**: `results`
 * - **Description**: Results
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResultsSlice = prismic.SharedSlice<
  "results",
  ResultsSliceVariation
>;

/**
 * Primary content in *RichTextWithButton → Primary*
 */
export interface RichTextWithButtonSliceDefaultPrimary {
  /**
   * id field in *RichTextWithButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_with_button.primary.ids
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ids: prismic.KeyTextField;

  /**
   * padding field in *RichTextWithButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_with_button.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  padding: prismic.KeyTextField;

  /**
   * text align field in *RichTextWithButton → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: rich_text_with_button.primary.text_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_align: prismic.SelectField<"left" | "center", "filled">;

  /**
   * title field in *RichTextWithButton → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_with_button.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * text field in *RichTextWithButton → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_with_button.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * button text field in *RichTextWithButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_with_button.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *RichTextWithButton → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_with_button.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for RichTextWithButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextWithButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextWithButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextWithButton*
 */
type RichTextWithButtonSliceVariation = RichTextWithButtonSliceDefault;

/**
 * RichTextWithButton Shared Slice
 *
 * - **API ID**: `rich_text_with_button`
 * - **Description**: RichTextWithButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextWithButtonSlice = prismic.SharedSlice<
  "rich_text_with_button",
  RichTextWithButtonSliceVariation
>;

/**
 * Primary content in *SimpleTwoColumn → Primary*
 */
export interface SimpleTwoColumnSliceDefaultPrimary {
  /**
   * title field in *SimpleTwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_two_column.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *SimpleTwoColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_two_column.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *SimpleTwoColumn → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_two_column.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SimpleTwoColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTwoColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleTwoColumnSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleTwoColumn*
 */
type SimpleTwoColumnSliceVariation = SimpleTwoColumnSliceDefault;

/**
 * SimpleTwoColumn Shared Slice
 *
 * - **API ID**: `simple_two_column`
 * - **Description**: SimpleTwoColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTwoColumnSlice = prismic.SharedSlice<
  "simple_two_column",
  SimpleTwoColumnSliceVariation
>;

/**
 * Primary content in *SingleOfficePage → Primary*
 */
export interface SingleOfficePageSliceDefaultPrimary {
  /**
   * image field in *SingleOfficePage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: single_office_page.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *SingleOfficePage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_office_page.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * address field in *SingleOfficePage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_office_page.primary.address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * phone field in *SingleOfficePage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_office_page.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone: prismic.RichTextField;

  /**
   * direction field in *SingleOfficePage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: single_office_page.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  direction: prismic.LinkField;

  /**
   * body text field in *SingleOfficePage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_office_page.primary.body_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_text: prismic.RichTextField;
}

/**
 * Default variation for SingleOfficePage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleOfficePageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SingleOfficePageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SingleOfficePage*
 */
type SingleOfficePageSliceVariation = SingleOfficePageSliceDefault;

/**
 * SingleOfficePage Shared Slice
 *
 * - **API ID**: `single_office_page`
 * - **Description**: SingleOfficePage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleOfficePageSlice = prismic.SharedSlice<
  "single_office_page",
  SingleOfficePageSliceVariation
>;

/**
 * Primary content in *SingleTeamPage → Primary*
 */
export interface SingleTeamPageSliceDefaultPrimary {
  /**
   * image field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * position field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * title field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * call text field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.call_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_text: prismic.KeyTextField;

  /**
   * cal link field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.cal_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cal_link: prismic.LinkField;

  /**
   * email text field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.email_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_text: prismic.KeyTextField;

  /**
   * email link field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.email_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email_link: prismic.LinkField;

  /**
   * body text field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.body_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_text: prismic.RichTextField;

  /**
   * education field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.education
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  education: prismic.RichTextField;

  /**
   * admissions field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.admissions
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  admissions: prismic.RichTextField;

  /**
   * Leadership Professional field in *SingleTeamPage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.primary.leadership
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  leadership: prismic.RichTextField;
}

/**
 * Primary content in *SingleTeamPage → Items*
 */
export interface SingleTeamPageSliceDefaultItem {
  /**
   * service text field in *SingleTeamPage → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.items[].service_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_text: prismic.KeyTextField;

  /**
   * service link field in *SingleTeamPage → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: single_team_page.items[].service_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service_link: prismic.LinkField;
}

/**
 * Default variation for SingleTeamPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleTeamPageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SingleTeamPageSliceDefaultPrimary>,
  Simplify<SingleTeamPageSliceDefaultItem>
>;

/**
 * Slice variation for *SingleTeamPage*
 */
type SingleTeamPageSliceVariation = SingleTeamPageSliceDefault;

/**
 * SingleTeamPage Shared Slice
 *
 * - **API ID**: `single_team_page`
 * - **Description**: SingleTeamPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleTeamPageSlice = prismic.SharedSlice<
  "single_team_page",
  SingleTeamPageSliceVariation
>;

/**
 * Primary content in *Team → Items*
 */
export interface TeamSliceDefaultItem {
  /**
   * image field in *Team → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * position field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * text field in *Team → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * button text field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *Team → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TeamSliceDefaultItem>
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Primary content in *TickList → Primary*
 */
export interface TickListSliceDefaultPrimary {
  /**
   * title field in *TickList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tick_list.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * columns field in *TickList → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 5
   * - **API ID Path**: tick_list.primary.columns
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  columns: prismic.SelectField<"5" | "3", "filled">;
}

/**
 * Primary content in *TickList → Items*
 */
export interface TickListSliceDefaultItem {
  /**
   * text field in *TickList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tick_list.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TickList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TickListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TickListSliceDefaultPrimary>,
  Simplify<TickListSliceDefaultItem>
>;

/**
 * Slice variation for *TickList*
 */
type TickListSliceVariation = TickListSliceDefault;

/**
 * TickList Shared Slice
 *
 * - **API ID**: `tick_list`
 * - **Description**: TickList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TickListSlice = prismic.SharedSlice<
  "tick_list",
  TickListSliceVariation
>;

/**
 * Primary content in *TwoColWithImage → Primary*
 */
export interface TwoColWithImageSliceDefaultPrimary {
  /**
   * title field in *TwoColWithImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_with_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *TwoColWithImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_with_image.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * text field in *TwoColWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * image field in *TwoColWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * button text field in *TwoColWithImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_with_image.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *TwoColWithImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_with_image.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for TwoColWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoColWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TwoColWithImage*
 */
type TwoColWithImageSliceVariation = TwoColWithImageSliceDefault;

/**
 * TwoColWithImage Shared Slice
 *
 * - **API ID**: `two_col_with_image`
 * - **Description**: TwoColWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColWithImageSlice = prismic.SharedSlice<
  "two_col_with_image",
  TwoColWithImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      PageDocument,
      PageDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      TeamDocument,
      TeamDocumentData,
      AllDocumentTypes,
      AppealSectionSlice,
      AppealSectionSliceVariation,
      AppealSectionSliceDefault,
      BadgesSlice,
      BadgesSliceVariation,
      BadgesSliceDefault,
      BannerWithBackgroundImageSlice,
      BannerWithBackgroundImageSliceVariation,
      BannerWithBackgroundImageSliceDefault,
      BlogPostSlice,
      BlogPostSliceVariation,
      BlogPostSliceDefault,
      ClientsRepresentSlice,
      ClientsRepresentSliceVariation,
      ClientsRepresentSliceDefault,
      ClientsRepresentSliceListLeftAlign,
      ColumnWithFaqSlice,
      ColumnWithFaqSliceVariation,
      ColumnWithFaqSliceDefault,
      CommercialBannerSlice,
      CommercialBannerSliceVariation,
      CommercialBannerSliceDefault,
      CtaSlice,
      CtaSliceVariation,
      CtaSliceDefault,
      FaqSlice,
      FaqSliceVariation,
      FaqSliceDefault,
      FaqWIthTitleSlice,
      FaqWIthTitleSliceVariation,
      FaqWIthTitleSliceDefault,
      GallerySlice,
      GallerySliceVariation,
      GallerySliceDefault,
      HeaderWithButtonsSlice,
      HeaderWithButtonsSliceVariation,
      HeaderWithButtonsSliceDefault,
      HomeBaneerSlice,
      HomeBaneerSliceVariation,
      HomeBaneerSliceDefault,
      HomeValuesSlice,
      HomeValuesSliceVariation,
      HomeValuesSliceDefault,
      IconBoxSlice,
      IconBoxSliceVariation,
      IconBoxSliceDefault,
      OfficesSlice,
      OfficesSliceVariation,
      OfficesSliceDefault,
      PageHeadingBannerSlice,
      PageHeadingBannerSliceVariation,
      PageHeadingBannerSliceDefault,
      PractiseAreaSlice,
      PractiseAreaSliceVariation,
      PractiseAreaSliceDefault,
      PreFooterSlice,
      PreFooterSliceVariation,
      PreFooterSliceDefault,
      RepresentativeColumnSlice,
      RepresentativeColumnSliceVariation,
      RepresentativeColumnSliceDefault,
      RepuTationBlockSlice,
      RepuTationBlockSliceVariation,
      RepuTationBlockSliceDefault,
      ResourcesSlice,
      ResourcesSliceVariation,
      ResourcesSliceDefault,
      ResultsSlice,
      ResultsSliceVariation,
      ResultsSliceDefault,
      RichTextWithButtonSlice,
      RichTextWithButtonSliceVariation,
      RichTextWithButtonSliceDefault,
      SimpleTwoColumnSlice,
      SimpleTwoColumnSliceVariation,
      SimpleTwoColumnSliceDefault,
      SingleOfficePageSlice,
      SingleOfficePageSliceVariation,
      SingleOfficePageSliceDefault,
      SingleTeamPageSlice,
      SingleTeamPageSliceVariation,
      SingleTeamPageSliceDefault,
      TeamSlice,
      TeamSliceVariation,
      TeamSliceDefault,
      TickListSlice,
      TickListSliceVariation,
      TickListSliceDefault,
      TwoColWithImageSlice,
      TwoColWithImageSliceVariation,
      TwoColWithImageSliceDefault,
    };
  }
}
