('use client;');

import React, { useEffect } from 'react';
import Footer from '@/components/footer/Footer';
import '@/styles/globals.css';
import localFont from 'next/font/local';
import Header from '@/commons/Header';
import Head from 'next/head';

const calluna = localFont({
  src: '../../public/fonts/Calluna-Regular.woff2',
  variable: '--calluna',
});

export default function App({ Component, pageProps }) {
  useEffect(() => {
    import('preline');
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />

        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/grids-responsive-min.css'
        ></link>
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'
          integrity='sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=='
          crossorigin='anonymous'
          referrerpolicy='no-referrer'
        />
      </Head>
      <div className={calluna.variable}>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </div>
    </>
  );
}
