import Appeals from '@/components/appeals/Appeals';
import React from 'react'
import Head from "next/head";
import Leadership from '@/components/appeal2/Leadership';
import FerIcons from '@/components/appeal3/FerIcons';
import Regrading from '@/components/regraDing/Regrading';
import Several from '@/components/several/Several';
import OnlyImg from '@/components/onlyImg/OnlyImg';
import UpperFoot from '@/components/upperFoot/UpperFoot';

const appeals = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css"
        />
      </Head>
      <Appeals />
      <Leadership />
     <FerIcons/>
     <Regrading/>
      <Several />
      <UpperFoot/>
     <OnlyImg/>
    </>
  );
}

export default appeals
