import React from 'react'
import Head from "next/head";
import Injury from '@/components/personal/Injury';
import Laywers from '../components/laywers/Laywers';
import Repu from '@/components/repuTation/Repu';
import GoodSign from '@/components/goodIcons/GoodSign';
import ShadoImg from '@/components/shado/ShadoImg';
import DropDouwn from '@/components/dropDown1/DropDouwn';
import AgainDrop from '@/components/againDrop/AgainDrop';
import OnlyImg from '@/components/onlyImg/OnlyImg';
import UpperFoot from '@/components/upperFoot/UpperFoot';
const personalinjury = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css"
        />
      </Head>
      <Injury />
      <Laywers />
      <Repu />
      <GoodSign />
      <ShadoImg />
      <DropDouwn />
      <UpperFoot/>
      <AgainDrop/>
      <OnlyImg />
    </>
  );
}

export default personalinjury
