import React from 'react'
import Head from "next/head";
import Testi from '@/components/testiMonial/Testi';
import TestiBox from '@/components/testiBox1/TestiBox';
import LastTesti from '@/components/testiLast/LastTesti';
import OnlyImg from '@/components/onlyImg/OnlyImg';
import UpperFoot from '@/components/upperFoot/UpperFoot';

const testimonials = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css"
        />
          </Head>
          <Testi/>
          <TestiBox/>
          <LastTesti/>
          <OnlyImg/>
          <UpperFoot/>
    </>
  );
}

export default testimonials
