import React from 'react'
import Hero from '@/components/transPortation/hero'
import Head from "next/head";
import Icons from '@/components/onlyIcons/Icons';
import OnlyImg from '@/components/onlyImg/OnlyImg';
import Repu from '@/components/repuTation/Repu';
import UpperFoot from '@/components/upperFoot/UpperFoot';
import Line from '@/components/line/Line';


const Transportation = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css"
        />
      </Head>

      <Hero />
      <Icons />
      <OnlyImg />
      <Line/>
      <Repu />
      <UpperFoot/>
    </>
  );
}

export default Transportation
