// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  clients_represent: dynamic(() => import("./ClientsRepresent")),
  commercial_banner: dynamic(() => import("./CommercialBanner")),
  cta: dynamic(() => import("./Cta")),
  home_baneer: dynamic(() => import("./HomeBaneer")),
  home_values: dynamic(() => import("./HomeValues")),
  practise_area: dynamic(() => import("./PractiseArea")),
  pre_footer: dynamic(() => import("./PreFooter")),
  two_col_with_image: dynamic(() => import("./TwoColWithImage")),
};
